import { Button, TextField } from "@mui/material";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import StockTable from "../src/components/organisms/stockTable";

const Home: NextPage = () => {
  useEffect(() => {
    axios.get(`/api/stock/stocks`).then((response) => {
      console.log("axios", response);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField id="standard-basic" label="Standard" variant="standard" />
      <Button variant="contained">検索</Button>
      <StockTable />
    </div>
  );
};

export default Home;
