import { Button, TextField } from "@mui/material";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import useSWR from "swr";
import StockTable from "../src/components/organisms/stockTable";

const fetcher = (url: string) => {
  console.log("API呼び出す", url);
  return fetch(url).then((r) => r.json());
};
const shouldFetch = false;

const Home: NextPage = () => {
  const [searchValue, setSearchValue] = useState("");
  const [click, setClick] = useState(false);
  const { data, error } = useSWR(
    click ? `/api/stock/stocks?q=${searchValue}` : null,
    fetcher
  );

  const handleChangeSearchValue = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchValue(e.target.value);
  };

  const handleClickSearchButton = () => {
    setClick((prev) => true);
  };

  if (data) {
    console.log("data", data);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField
        id="standard-basic"
        label="Standard"
        variant="standard"
        value={searchValue}
        onChange={handleChangeSearchValue}
      />
      <Button
        variant="contained"
        onClick={handleClickSearchButton}
        onBlur={() => setClick(false)}
      >
        検索
      </Button>
      {click ? "Clickされた" : "されてない"}
      {/* <StockTable data={data} /> */}
    </div>
  );
};

export default Home;
